// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: sum_calculation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetSumServiceClient is the client API for GetSumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetSumServiceClient interface {
	Dosum(ctx context.Context, in *GetSumRequest, opts ...grpc.CallOption) (*GetSumResponse, error)
}

type getSumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetSumServiceClient(cc grpc.ClientConnInterface) GetSumServiceClient {
	return &getSumServiceClient{cc}
}

func (c *getSumServiceClient) Dosum(ctx context.Context, in *GetSumRequest, opts ...grpc.CallOption) (*GetSumResponse, error) {
	out := new(GetSumResponse)
	err := c.cc.Invoke(ctx, "/greet.GetSumService/dosum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSumServiceServer is the server API for GetSumService service.
// All implementations must embed UnimplementedGetSumServiceServer
// for forward compatibility
type GetSumServiceServer interface {
	Dosum(context.Context, *GetSumRequest) (*GetSumResponse, error)
	mustEmbedUnimplementedGetSumServiceServer()
}

// UnimplementedGetSumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetSumServiceServer struct {
}

func (UnimplementedGetSumServiceServer) Dosum(context.Context, *GetSumRequest) (*GetSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dosum not implemented")
}
func (UnimplementedGetSumServiceServer) mustEmbedUnimplementedGetSumServiceServer() {}

// UnsafeGetSumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetSumServiceServer will
// result in compilation errors.
type UnsafeGetSumServiceServer interface {
	mustEmbedUnimplementedGetSumServiceServer()
}

func RegisterGetSumServiceServer(s grpc.ServiceRegistrar, srv GetSumServiceServer) {
	s.RegisterService(&GetSumService_ServiceDesc, srv)
}

func _GetSumService_Dosum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSumServiceServer).Dosum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GetSumService/dosum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSumServiceServer).Dosum(ctx, req.(*GetSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetSumService_ServiceDesc is the grpc.ServiceDesc for GetSumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetSumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GetSumService",
	HandlerType: (*GetSumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "dosum",
			Handler:    _GetSumService_Dosum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum_calculation.proto",
}
