// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: prime_number.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeFactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PrimeFactorRequest) Reset() {
	*x = PrimeFactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactorRequest) ProtoMessage() {}

func (x *PrimeFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prime_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactorRequest.ProtoReflect.Descriptor instead.
func (*PrimeFactorRequest) Descriptor() ([]byte, []int) {
	return file_prime_number_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeFactorRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeFactorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimeFactor uint64 `protobuf:"varint,1,opt,name=primeFactor,proto3" json:"primeFactor,omitempty"`
}

func (x *PrimeFactorResponse) Reset() {
	*x = PrimeFactorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactorResponse) ProtoMessage() {}

func (x *PrimeFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prime_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactorResponse.ProtoReflect.Descriptor instead.
func (*PrimeFactorResponse) Descriptor() ([]byte, []int) {
	return file_prime_number_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeFactorResponse) GetPrimeFactor() uint64 {
	if x != nil {
		return x.PrimeFactor
	}
	return 0
}

var File_prime_number_proto protoreflect.FileDescriptor

var file_prime_number_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x13, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x32, 0x60, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x75, 0x64, 0x69, 0x74, 0x73, 0x68, 0x61, 0x72,
	0x6d, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_number_proto_rawDescOnce sync.Once
	file_prime_number_proto_rawDescData = file_prime_number_proto_rawDesc
)

func file_prime_number_proto_rawDescGZIP() []byte {
	file_prime_number_proto_rawDescOnce.Do(func() {
		file_prime_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_number_proto_rawDescData)
	})
	return file_prime_number_proto_rawDescData
}

var file_prime_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_number_proto_goTypes = []interface{}{
	(*PrimeFactorRequest)(nil),  // 0: greet.PrimeFactorRequest
	(*PrimeFactorResponse)(nil), // 1: greet.PrimeFactorResponse
}
var file_prime_number_proto_depIdxs = []int32{
	0, // 0: greet.PrimeFactorService.GetPrimeFactors:input_type -> greet.PrimeFactorRequest
	1, // 1: greet.PrimeFactorService.GetPrimeFactors:output_type -> greet.PrimeFactorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_number_proto_init() }
func file_prime_number_proto_init() {
	if File_prime_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_number_proto_goTypes,
		DependencyIndexes: file_prime_number_proto_depIdxs,
		MessageInfos:      file_prime_number_proto_msgTypes,
	}.Build()
	File_prime_number_proto = out.File
	file_prime_number_proto_rawDesc = nil
	file_prime_number_proto_goTypes = nil
	file_prime_number_proto_depIdxs = nil
}
