// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: sum_calculation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 uint64 `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 uint64 `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *GetSumRequest) Reset() {
	*x = GetSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sum_calculation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumRequest) ProtoMessage() {}

func (x *GetSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sum_calculation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumRequest.ProtoReflect.Descriptor instead.
func (*GetSumRequest) Descriptor() ([]byte, []int) {
	return file_sum_calculation_proto_rawDescGZIP(), []int{0}
}

func (x *GetSumRequest) GetNum1() uint64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *GetSumRequest) GetNum2() uint64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type GetSumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetSumResponse) Reset() {
	*x = GetSumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sum_calculation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumResponse) ProtoMessage() {}

func (x *GetSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sum_calculation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumResponse.ProtoReflect.Descriptor instead.
func (*GetSumResponse) Descriptor() ([]byte, []int) {
	return file_sum_calculation_proto_rawDescGZIP(), []int{1}
}

func (x *GetSumResponse) GetResult() uint64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_sum_calculation_proto protoreflect.FileDescriptor

var file_sum_calculation_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x75, 0x6d, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x37,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6e,
	0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x64, 0x6f, 0x73, 0x75, 0x6d, 0x12, 0x14, 0x2e, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x75, 0x64, 0x69, 0x74,
	0x73, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x67, 0x6f, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sum_calculation_proto_rawDescOnce sync.Once
	file_sum_calculation_proto_rawDescData = file_sum_calculation_proto_rawDesc
)

func file_sum_calculation_proto_rawDescGZIP() []byte {
	file_sum_calculation_proto_rawDescOnce.Do(func() {
		file_sum_calculation_proto_rawDescData = protoimpl.X.CompressGZIP(file_sum_calculation_proto_rawDescData)
	})
	return file_sum_calculation_proto_rawDescData
}

var file_sum_calculation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sum_calculation_proto_goTypes = []interface{}{
	(*GetSumRequest)(nil),  // 0: greet.GetSumRequest
	(*GetSumResponse)(nil), // 1: greet.GetSumResponse
}
var file_sum_calculation_proto_depIdxs = []int32{
	0, // 0: greet.GetSumService.dosum:input_type -> greet.GetSumRequest
	1, // 1: greet.GetSumService.dosum:output_type -> greet.GetSumResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sum_calculation_proto_init() }
func file_sum_calculation_proto_init() {
	if File_sum_calculation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sum_calculation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sum_calculation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sum_calculation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sum_calculation_proto_goTypes,
		DependencyIndexes: file_sum_calculation_proto_depIdxs,
		MessageInfos:      file_sum_calculation_proto_msgTypes,
	}.Build()
	File_sum_calculation_proto = out.File
	file_sum_calculation_proto_rawDesc = nil
	file_sum_calculation_proto_goTypes = nil
	file_sum_calculation_proto_depIdxs = nil
}
